# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!

ec2:
  key_name: 'qfdeploy'
  key_path: '~/.ec2/qfdeploy.pem'
  access_key: 'xxxx'
  secret_access_key: 'xxxx'

build_steps:
  - './bootstrap'
  - './configure'
  - 'make'

acceptance_test_steps:
  - 'cd test && ./runat 5001'

builds:
  trunk_fedora8:
    desc:  'fedora core 8, gcc 4.1, 32-bit'
    image: 'fedora8_32'
    repo: 'git://github.com/shanetrotter/qf-temp.git'

images:
  fedora8_32: 'ami-4308ee2a'
