# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!

ec2:
  key_name: 'qfdeploy'
  key_path: '~/.ec2/qfdeploy.pem'
  access_key: 'xxxx'
  secret_access_key: 'xxxx'

build_steps:
  - './bootstrap'
  - './configure'
  - 'make'

acceptance_test_steps:
  - 'cd test && ./runat 5001'

builds:
  trunk_fedora8:
    desc:  'fedora core 8, gcc 4.1, 32-bit'
    image: 'fedora8_32_gcc41'
    repo: 'git://github.com/quickfix/quickfix.git'

  trunk_centos5_gcc41:
    desc:  'centos 5.0, gcc 4.1, 64-bit'
    image: 'centos_5_0_64_gcc41'
    repo: 'git://github.com/quickfix/quickfix.git'

  trunk_centos4_gcc41:
    desc:  'centos 4.7, gcc 3.4, 64-bit'
    image: 'centos_4_7_gcc34'
    repo: 'git://github.com/quickfix/quickfix.git'

  trunk_ubuntu_gcc43:
    desc:  'ubuntu 9.04, gcc 4.3.3, 32-bit'
    image: 'ubuntu_9_04_gcc433'
    repo: 'git://github.com/quickfix/quickfix.git'

images:
  fedora8_32_gcc41:    'ami-4308ee2a'
  centos_5_0_64_gcc41: 'ami-754fa91c'
  centos_4_7_gcc34:    'ami-bfa140d6'
  ubuntu_9_04_gcc433:  'ami-f3b2539a'
