# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!

key_name: 'qfdeploy'
key_path: '~/.ec2/qfdeploy.pem'
access_key: 'xxxxxxxxx'
secret_access_key: 'xxxxxxxxx'
results_path: '.'

builds:
  fedora8_trunk:
    desc:  'fedora core 8, gcc 4.1, 32-bit'
    image: 'fedora8_32'
    repo: 'git://github.com/shanetrotter/qf-temp.git'

images:
  fedora8_32: 'ami-4308ee2a'
