# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!
# !!!!!!!!!! DO NOT CHECK THIS IN WITH SECRET KEYS !!!!!!!!!!!!!!

ec2:
  key_name: 'qfdeploy'
  key_path: '~/.ec2/qfdeploy.pem'
  access_key: 'xxxxxxxxxxxxxxx'
  secret_access_key: 'xxxxxxxxxxxxxxx'

build_steps:
  - 'step 1'
  - 'step 2'
  - 'step 3'

make_steps:
  - 'step 4'
  - 'step 5'
  - 'step 6'

builds:
  fedora8_trunk:
    desc:  'fedora core 8, gcc 4.1, 32-bit'
    image: 'fedora8_32'
    repo: 'git://github.com/shanetrotter/qf-temp.git'

images:
  fedora8_32: 'ami-4308ee2a'
